export const ACTUALIZAR = 'POSTS_ACTUALIZAR';
export const LOADING = 'POSTS_LOADING';
export const ERROR = 'POSTS_ERROR';
export const COM_ERROR = 'COMENTARIOS_ERROR';
export const COM_LOADING = 'COMENTARIOS_LOADING';
export const COM_ACTUALIZAR = 'COMENTARIOS_ACTUALIZAR';
